# main.tf — Cloudflare Workers deployment for odoo-mcp-server
#
# Architecture:
#   cloudflare_worker           — the Worker resource (name + account)
#   cloudflare_worker_version   — immutable version: JS shim + WASM module
#   cloudflare_workers_deployment — deploys the version (explicit, separate)
#   cloudflare_workers_secret   — Odoo credentials as encrypted secrets
#   cloudflare_workers_route    — routes mcp.dapla.net/* to the Worker
#
# NOTE on WASM + Terraform (provider v5 known issue #6852):
#   cloudflare_worker_version does NOT yet support uploading a separate
#   .wasm module alongside the JS entrypoint via multi-part form upload.
#   Workaround: the JS shim (worker_bundle.js) is a self-contained bundle
#   where the WASM bytes are base64-inlined by the CI build step before
#   Terraform runs. The bundle is a single file upload — no separate
#   wasm_module binding needed.
#   See: https://github.com/cloudflare/terraform-provider-cloudflare/issues/6852
#   When the provider fixes this, replace bundle with:
#     main_module = "worker.js"
#     modules = [{ name = "odoo-mcp.wasm", content_file = "../odoo-mcp.wasm",
#                  type = "application/wasm" }]

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# ── Worker (parent resource) ─────────────────────────────────────────── #

resource "cloudflare_worker" "odoo_mcp" {
  account_id = var.cloudflare_account_id
  name       = var.worker_name
}

# ── Worker version — self-contained JS bundle with inlined WASM ──────── #
# The bundle is produced by the CI build step:
#   ./nob wasm                                     → odoo-mcp.wasm
#   node scripts/bundle_wasm.js                    → worker_bundle.js
# The bundle_wasm.js script reads odoo-mcp.wasm, base64-encodes it,
# and injects it into worker.js as a WebAssembly.Module literal.

resource "cloudflare_worker_version" "odoo_mcp" {
  account_id  = var.cloudflare_account_id
  worker_id   = cloudflare_worker.odoo_mcp.id

  # Single self-contained module (JS + inlined WASM)
  # Generated by CI: scripts/bundle_wasm.js → worker_bundle.js
  content_file       = "${path.module}/../workers/worker_bundle.js"
  compatibility_date = var.compatibility_date

  # Worker metadata
  usage_model = "standard"
}

# ── Deployment — explicit, separate from version creation ────────────── #

resource "cloudflare_workers_deployment" "odoo_mcp" {
  account_id  = var.cloudflare_account_id
  worker_id   = cloudflare_worker.odoo_mcp.id
  version_id  = cloudflare_worker_version.odoo_mcp.id
  percentage  = 100
}

# ── Secrets — Odoo credentials, encrypted at rest by Cloudflare ──────── #

resource "cloudflare_workers_secret" "odoo_url" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.odoo_mcp.name
  name        = "ODOO_URL"
  text        = var.odoo_url

  depends_on = [cloudflare_worker.odoo_mcp]
}

resource "cloudflare_workers_secret" "odoo_db" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.odoo_mcp.name
  name        = "ODOO_DB"
  text        = var.odoo_db

  depends_on = [cloudflare_worker.odoo_mcp]
}

resource "cloudflare_workers_secret" "odoo_user" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.odoo_mcp.name
  name        = "ODOO_USER"
  text        = var.odoo_user

  depends_on = [cloudflare_worker.odoo_mcp]
}

resource "cloudflare_workers_secret" "odoo_api_key" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.odoo_mcp.name
  name        = "ODOO_API_KEY"
  text        = var.odoo_api_key

  depends_on = [cloudflare_worker.odoo_mcp]
}

resource "cloudflare_workers_secret" "cors_origins" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.odoo_mcp.name
  name        = "CORS_ORIGINS"
  text        = var.cors_origins

  depends_on = [cloudflare_worker.odoo_mcp]
}

# ── Route — mcp.dapla.net/* → Worker ─────────────────────────────────── #

resource "cloudflare_workers_route" "odoo_mcp" {
  zone_id  = var.cloudflare_zone_id
  pattern  = var.worker_route
  script   = cloudflare_worker.odoo_mcp.name

  depends_on = [cloudflare_workers_deployment.odoo_mcp]
}
